export const HOST = import.meta.env.VITE_SERVER_URL;
export const AUTH_ROUTES = "api/auth";
export const ACCOUNT_ROUTES ="api/account"
export const SIGNUP_ROUTE = `${AUTH_ROUTES}/signup`;
export const LOGIN_ROUTE = `${AUTH_ROUTES}/login`;
export const GET_USER_INFO = `${AUTH_ROUTES}/user-info`;
export const UPDATE_PROFILE_ROUTE = `${AUTH_ROUTES}/update-profile`;
export const ADD_PROFILE_IMAGE_ROUTE = `${AUTH_ROUTES}/add-profile-image`;
export const REMOVE_PROFILE_IMAGE_ROUTE = `${AUTH_ROUTES}/remove-profile-image`;
export const LOGOUT_ROUTE = `${AUTH_ROUTES}/logout`;
export const ADD_ACCOUNT =  `${ACCOUNT_ROUTES}/add_account`
export const DELETE_ACCOUNT =  `${ACCOUNT_ROUTES}/delete_account`
export const EDIT_ACCOUNT =  `${ACCOUNT_ROUTES}/edit_account`
export const ADD_TRANSATION =  `${ACCOUNT_ROUTES}/add_transation`
export const DELETE_TRANSATION =  `${ACCOUNT_ROUTES}/delete_transation`
export const EDIT_TRANSATION =  `${ACCOUNT_ROUTES}/edit_transation`
